widget:
  # Path of the folder containing the widget to test
  folder:
  # List of parameters of the widgets. Parameters of the category should be also included
  parameters:
    WIDGET_PARAMETER_1: value1
    WIDGET_PARAMETER_2: value2
    WIDGET_CATEGORY_PARAMETER_1: value3
  # Mocked previous data of the widget. Only use it if you need to compute something between the current data and the previous data
  previousData: '{}'

# Execute the widget behind a proxy
proxy:
  host:
  port:
  noProxyDomains:
