  
name: Release

on:
  push:
    tags:
      - "v*.*.*" 
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_CD_TOKEN }}

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Package application
        run: mvn -B -DskipTests package -P production
        
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.CI_CD_TOKEN }}
          bodyFile: "CHANGELOG.md"
          artifacts: "target/suricate-widget-tester.jar"
          name: Release ${GITHUB_REF##*/}
